Repository upmind-automation/provision-provider-base, pull requests merged in 2024-02, with the labels that each got.

#18 #16 Add return types for console commands
  src/Laravel/Console/CacheRegistry.php
  src/Laravel/Console/ClearRegistryCache.php
  src/Laravel/Console/ListRegistry.php
  src/Laravel/Console/SummarizeRegistry.php
Labels: enhancement

#19 #15 Support for Laravel 10 and PHP 8.3
  composer.json
Labels: enhancement

#22 #21 - Added phpunit to dev requirements
  composer.json
Labels: enhancement

#28 #27 - Fixed invalid variable name used for static error message
  src/Exception/RegistryError.php
Labels: bug, static analysis

#29 #26 - Added missing property (it was auto-set when setter executed)
  src/Provider/Helper/Api/Response.php
Labels: static analysis

#32 #30 - Change call to static::getType() to prevent phpstan issue
  src/AttributeQuery/AbstractElement.php
Labels: static analysis

#31 #25 - Resolve unsafe usage new static static analysis issue
  src/Exception/RegistryError.php
  src/Laravel/Html/HtmlField.php
  src/Provider/DataSet/DataSet.php
  src/Provider/Helper/Exception/ConfigurationError.php
Labels: static analysis

#41 #40 - Fix php8 static analysis issues
  .github/workflows/static-analysis.yml
  composer.json
  src/AttributeQuery/AbstractElement.php
  src/Exception/RegistryError.php
  src/Laravel/Html/HtmlField.php
  src/Provider/DataSet/DataSet.php
  src/Provider/DataSet/Rules.php
  src/Provider/Helper/Exception/ConfigurationError.php
Labels: static analysis
